version: 3

services:
  nginx:
  image: nginx
  container_name: nginx
  volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./html:/usr/share/nginx/html
    - ./images:/usr/share/nginx/images
  ports:
    - '80:80'
